// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebbSite.Common.Models.DbModels;

#nullable disable

namespace WebbSite.Common.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20260621090214_v001")]
    partial class v001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("WebbSite.Common.Models.DbModels.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("StockCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("WebbSite.Common.Models.DbModels.StockCCASS", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StakeInCCASS")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockCode")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TopFive")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopTen")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TopTenNCIP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StockCCASS");
                });
#pragma warning restore 612, 618
        }
    }
}
